// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 10:42:06 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/kimlarocca/Websites/ciatt-gpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/plugins/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/ciatt-gpt/composables/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/ciatt-gpt/utils/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/ciatt-gpt/pages/index.vue","/Users/kimlarocca/Websites/ciatt-gpt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/ciatt-gpt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;